create or replace view xsckmx_vw as
select fid,
       djbh,
       zdrq,
       cch,
       wldwid,
       xsfs,
       hdbz,
       mx.id,
       wlid,
       pm,
       ph,
       ggxh,
       jldwid,
       sfsl,
       dwcb,
       dj,
       dj * to_number(substr(ggxh, 1, 2)) * 0.001 bdj,
       sfsl * 1000 / to_number(substr(ggxh, 1, 2)) bs,
       
       DJZT,
       zy,
       bz,
       sfkp,
       xstdid,
       pch
  from (select id,
               djbh,
               cch,
               zdrq,
               wldwid,
               '赊销' xsfs,
               hdbz,
               DJZT,
               bz zy,
               xstdid
          from kcckd1_tb
         where djlxid = 6) zb,
       (select id,
               fid,
               wlid,
               pm,
               ph,
               ggxh,
               jldwid,
               sfsl,
               0 dwcb,
               dj,
               bz,
               sfkp,
               pch
          from kcckd2_tb
         where ggxh is not null
           and trim(ggxh) <> '散装') mx
 where zb.id = mx.fid
union all
select fid,
       djbh,
       zdrq,
       cch,
       wldwid,
       xsfs,
       hdbz,
       mx.id,
       wlid,
       pm,
       ph,
       ggxh,
       jldwid,
       sfsl,
       dwcb,
       dj,
       null bdj,
       null bs,
       DJZT,
       zy,
       bz,
       sfkp,
       xstdid,
       pch
  from (select id,
               djbh,
               cch,
               zdrq,
               wldwid,
               '赊销' xsfs,
               hdbz,
               DJZT,
               bz zy,
               xstdid
          from kcckd1_tb
         where djlxid = 6) zb,
       (select id,
               fid,
               wlid,
               pm,
               ph,
               ggxh,
               jldwid,
               sfsl,
               0 dwcb,
               dj,
               bz,
               sfkp,
               pch
          from kcckd2_tb
         where ggxh is null
            or trim(ggxh) = '散装') mx
 where zb.id = mx.fid